### ISSUE TITLE
Responsive function: obtain privacy policy

### ISSUE THREAD

**Issue by pmonks** [pmonks/futbot#81]
From @IGJoshua just now:

> as a part of the new dev ToS you need to publish a privacy policy which is accessible to anyone using your bot (so maybe a privacy command which dms it to them, or a link in your presence which gives them the privacy policy).

Given the current design of the bot, this is probably best achieved via a responsive chat function e.g. `!policy` or `!privacy` or similar.  It may also be worth including additional information (like a link to this GitHub repository) in that message too, for added transparency.

**Comment by IGJoshua** [comment]
Something I recommend for all bots, although this is mostly directed at bots meant for multiple guilds, is to have a help command, a prefix changing command accessible to admins/server managers, and one for privacy policy which are under a ping of the bot, but not any prefix. That way a user doesn't have to know the bot's prefix to get basic information about it.

**Comment by pmonks** [comment]
Privacy policy added in rev 19b6a5091b8571434e0b6310bcd07c21358e639c.  Will have the bot link to it there, for ease of maintenance.

**Comment by pmonks** [comment]
Fixed in rev #e504fe3f6331b5eaf909addc43671f54f907dfde
